Repository abracm/display-latam, pull requests merged in 2024-08, with the labels that each got.

#18 Include expected best practices in the README
  README.md
Labels: documentation

#15 Improved code readability, moved led display font to it's own header file, moved main file to display-latam folder inside SRC
  src/display-latam/display-latam.ino
  src/display-latam/xantofont.cpp
  src/display-latam/xantofont.h
Labels: enhancement

#21 Led intensity bug fix and config file
  src/display-latam/config.h
  src/display-latam/display-latam.ino
Labels: bug, enhancement
